[build]
  command = "pnpm run build"
  publish = ".next"

[build.environment]
  PNPM_FLAGS = "--shamefully-hoist"
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
