CREATE INDEX idx_products_category ON products(category_id) WHERE is_active = true;
CREATE INDEX idx_products_brand ON products(brand_id) WHERE is_active = true;
CREATE INDEX idx_products_featured ON products(is_featured) WHERE is_featured = true AND is_active = true;
CREATE INDEX idx_products_search ON products USING GIN(search_vector);
CREATE INDEX idx_product_variants_product ON product_variants(product_id) WHERE is_active = true;
CREATE INDEX idx_product_variants_sku ON product_variants(sku);
CREATE INDEX idx_orders_customer ON orders(customer_id);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_created ON orders(created_at DESC);
CREATE INDEX idx_orders_number ON orders(order_number);
CREATE INDEX idx_order_items_order ON order_items(order_id);
CREATE INDEX idx_order_items_variant ON order_items(variant_id);
CREATE INDEX idx_loyalty_tx_customer ON loyalty_points_transactions(customer_id);
CREATE INDEX idx_loyalty_tx_created ON loyalty_points_transactions(created_at DESC);
CREATE INDEX idx_exchange_customer ON exchange_requests(customer_id);
CREATE INDEX idx_exchange_status ON exchange_requests(status);
CREATE INDEX idx_exchange_order ON exchange_requests(order_id);
CREATE INDEX idx_notifications_recipient ON notifications(recipient_id, is_read);
CREATE INDEX idx_notifications_created ON notifications(created_at DESC);
CREATE INDEX idx_audit_actor ON audit_logs(actor_id);
CREATE INDEX idx_audit_entity ON audit_logs(entity_type, entity_id);
CREATE INDEX idx_audit_created ON audit_logs(created_at DESC);
CREATE INDEX idx_customer_referral ON customer_profiles(referral_code);
CREATE INDEX idx_customer_email ON customer_profiles(email);
